apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: application
spec:
  type: ClusterIP
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

