name: java-ci

on:
    push:
        branches: [ "main" ]
        paths-ignore:
          - 'java-app/**'
          - 'kubernetes/**'
    pull_request:
        branches: [ "main" ]
        paths-ignore:
          - 'java-app/**'
          - 'kubernetes/**'
    workflow_dispatch:

jobs:
    gitleaks:
        name: secrets scanning
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7
            - name: Gitleaks
              uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    lint:
      name: super-linter
      runs-on: ubuntu-latest
      permissions:
      # contents permission to clone the repository
        contents: read
        packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
        issues: write
        pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
        statuses: write
      steps:
         - name: Checkout code
           uses: actions/checkout@v7
           with:
            fetch-depth: 0

         - name: Super-linter
           uses: super-linter/super-linter@v8.7.0
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BRANCH: main
            FILTER_REGEX_INCLUDE: ^src/.*
            VALIDATE_JAVA: true
            VALIDATE_GOOGLE_JAVA_FORMAT: true
    build-test-analyse:
      name: application-building-testing-analysing
      needs: ["lint","gitleaks"]
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: setup java
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        # - name: download dependencies  === maven automatically downloads dependencies
        #   run: mvn dependency:go-offline
        - name: build application
          run: mvn clean package -DskipTests
        - name: test application
          run: mvn test
        -  name: analyze
           env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
            mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Keerthan2006_java-devsecops-cicd \
            -Dsonar.qualitygate.wait=true 
    docker:
      name: docker push 
      needs: ["build-test-analyse"]
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: docker login
          uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: docker build
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }} .
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
          with:
            image-ref: '${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
        - name: docker push
          run: docker push ${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }}
    update-tag:
      permissions:
        contents: write
      name: helm-tag
      needs: docker
      runs-on: ubuntu-latest
      env:
        SECRET: ${{ secrets.email }}
      steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: update tag
          run: |
            sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" java-app/values.yaml
        - name: git add-push
          run: |
            git config --global user.name ${{ vars.username }}
            git config --global user.email "$SECRET"
            git add java-app/values.yaml
            git diff --cached --quiet || git commit -m "updating helm value"
            git push
    dast:
      name: dast test
      runs-on: ubuntu-latest
      needs: update-tag
      steps:
        - name: app check
          run: |
            for i in {1..30}; do
              if curl -f http://k8s-applicat-javaing-efc46936cd-1242321223.ap-south-1.elb.amazonaws.com/health; then
                echo "app is running"
                exit 0
              fi
              echo "waiting for app"
              sleep 10
            done
            echo "app failed to run"
            exit 1
        - name: OWASP ZAP Baseline Scan
          uses: zaproxy/action-baseline@v0.14.0
          with:
            target: 'http://k8s-applicat-javaing-efc46936cd-1242321223.ap-south-1.elb.amazonaws.com'
            #rules_file_name: '.zap/rules.tsv'   # optional custom rules
            cmd_options: '-a'                  # '-a' = include alpha passive scan rules

        - name: Upload ZAP Report
          uses: actions/upload-artifact@v4
          with:
            name: zap-scan-report
            path: report_html.html
