name: java-ci

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    gitleaks:
        name: secretes scanning
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7
            - name: install
              run: sudo apt update && sudo apt install gitleaks
            - name: scan
              run: gitleaks detect --source . --verbose
    lint:
      name: super-linter
      runs-on: ubuntu-latest
      permissions:
      # contents permission to clone the repository
        contents: read
        packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
        issues: write
        pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
        statuses: write
      steps:
         - name: Checkout code
           uses: actions/checkout@v7
           with:
            fetch-depth: 0

         - name: Super-linter
           uses: super-linter/super-linter@v8.7.0
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BRANCH: main
            FILTER_REGEX_INCLUDE: ^src/.*
            VALIDATE_JAVA: true
            VALIDATE_GOOGLE_JAVA_FORMAT: true
    build-test-analyse:
      name: application-building-testing-analysing
      needs: ["lint","gitleaks"]
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: setup java
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        # - name: download dependencies  === maven automatically downloads dependencies
        #   run: mvn dependency:go-offline
        - name: build application
          run: mvn clean package -DskipTests
        - name: test application
          run: mvn test
        -  name: analyze
           env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
            mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Keerthan2006_java-devsecops-cicd \
            -Dsonar.qualitygate.wait=true 
    docker:
      name: docker push 
      needs: ["build-test-analyse"]
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: docker login
          uses: docker/login-action@49c5831d4b169f744e666596d51a030a35255268
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: docker build
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }} .
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@49c5831d4b169f744e666596d51a030a35255268
          with:
            image-ref: '${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
        - name: docker push
          run: docker push ${{ vars.DOCKERHUB_USERNAME }}/java-app-deploy:${{ github.sha }}