name: java-ci

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    gitleaks:
        name: secretes scanning
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7
            - name: install
              run: sudo apt update && sudo apt install gitleaks
            - name: scan
              run: gitleaks detect --source . --verbose
    lint:
      name: super-linter
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v7
           with:
            fetch-depth: 0

         - name: Super-linter
           uses: super-linter/super-linter@v8.7.0
           env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BRANCH: main
            FILTER_REGEX_INCLUDE: .*src/.*